---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      when: ansible_os_family == "Debian"
  
  vars:
    php_version: "8.3"
    php_webserver: apache2
    install_composer: true
    install_xdebug: true
    
  roles:
    - role: php